# Generated by Django 5.2.17 on 2026-08-31 15:24

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_image_alter_project_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-year', 'sort_order', 'title']},
        ),
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='project',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Size as shown to buyers, for example 25 × 90 m (2,250 m²).', max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, help_text='City or site, if it can be named.', max_length=160),
        ),
        migrations.AddField(
            model_name='project',
            name='work_type',
            field=models.CharField(blank=True, choices=[('assembly', 'Assembly'), ('renovation', 'Renovation'), ('repair', 'Repair'), ('facade', 'Façade')], max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='projects/', validators=[core.validators.validate_image_file], verbose_name='Cover image'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='projects/images/', validators=[core.validators.validate_image_file])),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.project')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
