# Generated by Django 5.2.17 on 2026-09-01 04:58

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_project_options_project_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('summary', models.TextField(help_text='Short pitch for distributors. Do not publish prices here.')),
                ('file', models.FileField(blank=True, help_text='Spec or catalog PDF. Prefer a no-price file; volume prices stay on the quote.', upload_to='wholesale/', validators=[core.validators.validate_document_file], verbose_name='Catalog PDF')),
                ('image', models.ImageField(blank=True, upload_to='wholesale/covers/', validators=[core.validators.validate_image_file], verbose_name='Cover image')),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'wholesale catalog',
                'verbose_name_plural': 'wholesale catalogs',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
