# Generated by Django 5.2.17 on 2026-08-31 13:44

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_technical_text_productspecification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='file',
            field=models.FileField(upload_to='products/documents/', validators=[core.validators.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='file',
            field=models.ImageField(upload_to='products/images/', validators=[core.validators.validate_image_file]),
        ),
    ]
